# Generated by Django 4.2.7 on 2023-11-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CvUser', models.CharField(max_length=20, unique=True)),
                ('CvPerson', models.CharField(max_length=20, unique=True)),
                ('Login', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=128)),
                ('FecIni', models.DateField()),
                ('FecFin', models.DateField()),
                ('EdoCta', models.BooleanField(default=False)),
            ],
        ),
    ]
