# Generated by Django 4.2.7 on 2023-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musuario',
            name='CvPerson',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='musuario',
            name='Login',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
