# Generated by Django 4.2.7 on 2023-11-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_musuario_cvperson_alter_musuario_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='musuario',
            name='CvUser',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
