# Generated by Django 4.2.6 on 2023-11-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mUsuario',
        ),
    ]
