# Generated by Django 4.2.6 on 2023-11-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_musuario_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mUsuario',
        ),
    ]
