# Generated by Django 4.2.6 on 2023-11-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cvPersona',
            field=models.IntegerField(),
        ),
    ]
