# Generated by Django 4.2.6 on 2023-11-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_cvpersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cvPersona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
