# Generated by Django 4.2.6 on 2023-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
