# Generated by Django 4.2.6 on 2023-11-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_dateend'),
    ]

    operations = [
        migrations.CreateModel(
            name='mPersona',
            fields=[
                ('CvPersona', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('ApePat', models.CharField(max_length=20)),
                ('ApeMat', models.CharField(max_length=20)),
                ('Direccion', models.TextField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('Trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('FecNac', models.DateTimeField(blank=True, null=True)),
                ('TpPerson', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], default='N', max_length=1)),
            ],
        ),
    ]
